# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: AWS ECR
    # You may pin to the exact commit or the version.
    # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
      uses: kciter/aws-ecr-action@v4
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.ACCESS_ID }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.ACCESS_KEY }}
        # AWS Account ID
        account_id: ${{ secrets.ACCOUNT_ID }}
        # A role to assume under the account_id account.
        # Name of your ECR repository
        repo: calvin-registry
        # The AWS region
        region: ap-southeast-1
        # Set this to true to create the repository if it does not already exist
        #create_repo: # optional
        # Set this to true to set a policy on the repository
        #set_repo_policy: # optional
        # Set this to repository policy statement json file. only used if the set_repo_policy is set to true
        #repo_policy_file: # optional, default is repo-policy.json
        # Comma-separated string of ECR image tags
        tags: v1.1
        # Name of Dockerfile to use
        dockerfile: Dockerfile

        
